### ISSUE TITLE
Change '|' to a more accessible key or pattern

### ISSUE THREAD

**Issue by sahilsignup** [asmpro7/AudFlow#4]
Hello, hope you are doing well! Thank you for the very useful plugin!

Currently, the plugin requires the user to type the key '|'.

Although this works, there is a problem:
On other keyboards - for example, on French keyboards - the key '|' is difficult to type.

As such, it may be more ideal if this key were — if possible — made customizable, or changed to a more accessible key, such as ';' or '-'.
Or — which in fact may be more ideal — if instead of a key, a pattern which is not normally entered naturally, was used, such as ':::' or '...'.

This would make the plugin more accessible, faster to use, and ultimately more ideal for all users.

Thank you for your consideration, and have a great day!

**Comment by asmpro7** [comment]
thanks to mention that, 
I will make it customizable from flow ui in addition to the normal way "|" for old users who get used to it,
the customizable key will be by default ";"  until user change it. 
stay tuned to v2.0.5, it will release soon 

thanks again for your time to make the plugin good. 🫀

**Comment by asmpro7** [comment]
Sorry for making a late update 
last few weeks I have had final exams 😅

## the ability to customize the execute key is now available in v2.1.0 
it will be available soon in flow (at most 24 hours)
![image](https://github.com/asmpro7/AudFlow/assets/114514662/6b95a043-76dc-4958-a7dc-f30787d283fb)

If you have any questions or any ideas tell me 
and sorry again for the late update
